name: Deploy GCP Bucket with Workload Identity Federation

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Or your environment

    permissions:
      contents: read
      id-token: write # Required for workload identity federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure GCP Credentials (Workload Identity Federation)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: //iam.googleapis.com/projects/1029432129682/locations/global/workloadIdentityPools/github-demo/providers/github
          service_account: github-wif@red-abstraction-446113-u1.iam.gserviceaccount.com # The service account to impersonate

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
       # env:
          #TF_VAR_bucket_name: my-unique-bucket-${{ github.sha }}
          #TF_VAR_region: us-central1
          # Add other variables as needed

      - name: Terraform Apply
        #if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
       # env:
          #TF_VAR_bucket_name: my-unique-bucket-${{ github.sha }}
          #TF_VAR_region: us-central1
          # Add other variables as needed

      - name: Output Bucket Name (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          bucket_name=$(terraform output -json bucket_name | jq -r .)
          echo "Bucket Name: $bucket_name"
